spring.application.name=rodojacto

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/rodojacto_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:rodo1234jacto}

# JWT Security
api.security.token.secret=${JWT_SECRET:dvgAvrK49yCXE1ioUupY9S6Ag971cG1GHsOC3alMrwjfzDIyba9RO1vwb4z6ecP6}

# Configuração JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitando o Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration